# Generated by Django 4.0.1 on 2022-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameKeeper', '0002_building_is_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='holder',
            field=models.CharField(default='Nobody', max_length=50),
        ),
    ]
