# Generated by Django 4.0.1 on 2022-03-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameKeeper', '0007_remove_building_capture_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='capture_date2',
            new_name='capture_date',
        ),
    ]
