# Generated by Django 4.0.1 on 2022-02-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='point_total',
            field=models.IntegerField(default=0),
        ),
    ]
