# Generated by Django 3.2.12 on 2022-03-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('territoryGame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='territorycapture',
            name='username',
        ),
        migrations.AddField(
            model_name='territorycapture',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='group.group', verbose_name='Holder'),
        ),
    ]
