# Generated by Django 3.2.12 on 2022-03-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('territoryGame', '0003_alter_territorycapture_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorycapture',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='group.group', verbose_name='Holder'),
        ),
    ]
