# Generated by Django 3.2.12 on 2022-02-28 21:33

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, validators=[account.models.validate_email], verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_gameKeeper', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
