# Generated by Django 3.2.12 on 2022-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameKeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='holder',
            field=models.CharField(default='Nobody', max_length=50),
        ),
    ]
