# Generated by Django 4.0.1 on 2022-03-22 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameKeeper', '0003_auto_20220315_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='capture_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
