# Generated by Django 4.0.1 on 2022-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameKeeper', '0004_building_capture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='capture_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
