# Generated by Django 4.0.1 on 2022-03-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameKeeper', '0005_alter_building_capture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='capture_date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
