# Generated by Django 3.2.12 on 2022-02-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220222_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
    ]
