# Generated by Django 3.2.12 on 2022-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameKeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_captured',
            field=models.BooleanField(default=False),
        ),
    ]
