# Generated by Django 3.2.12 on 2022-02-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_gameKeeper',
            field=models.BooleanField(default=False),
        ),
    ]
