# Generated by Django 3.2.12 on 2022-02-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_gamekeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
    ]
