# Generated by Django 4.0.1 on 2022-02-28 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_delete_team'),
        ('account', '0004_auto_20220223_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='belongs_to_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
    ]
