# Generated by Django 4.0.1 on 2022-02-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
