# Generated by Django 4.0.1 on 2022-02-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_score_delete_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='score',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
