# Generated by Django 3.2.12 on 2022-03-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('account', '0007_alter_account_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='belongs_to_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
    ]
